<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/include/head.phtml' ?>
</head>
<body>
    <div class="min-f-full">
        <nav>
            <div class="container">
                <div class="flex items-center">
                    <a href="/" class="nav-item">Home</a>
                    <a href="/products" class="nav-item">Products</a>
                    <a href="/contact" class="nav-item">Contact</a>
                </div>
            </div>
        </nav>

        <header>
            <div class="container">
                <h1 id="page-title">Home</h1>
            </div>
        </header>

        <main>
            <div class="container" style="padding: 2rem 0;">
                My main content here
            </div>
        </main>
    </div>
</body>
</html>
